apiVersion: v1
kind: Namespace
metadata:
  name: dotnetcore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetcore
  namespace: dotnetcore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherforecast
      stage: prod
      release: stable
      tier: "application"
      product: "dotnetcoreapi"
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
        dynatrace/instrument: 'false'
        pipeline.stage: prod-stable
        pipeline.build: 2.3.1.3476
        pipeline.project: sockshop
        support.contact: 'john.doe@sockshop.com'
        support.channel: '#support-sockshop-services'
      labels:
        app: ace
        stage: prod
        release: stable
        tier: 'messaging'
        product: 'ibm-ace'
    spec:
      containers:
      - name: ace
        image: wabbo/mydotnetcoreapi:latest
        env:
        - name: NODENAME
          value: MYNODE
        - name: SERVERNAME
          value: MYMBSERVER
        - name: LICENSE
          value: accept
        - name: ACE_ENABLE_METRICS
          value: 'true'
        - name: DT_CLUSTER_ID
          value: 'ace-production'
        - name: DT_RELEASE_BUILD_VERSION
          value: '2021-12-12'          
        - name: DT_RELEASE_VERSION
          value: '1.0.1'
        - name: DT_RELEASE_PRODUCT
          value: 'ACME Messaging'
        - name: DT_RELEASE_STAGE
          value: 'User-Acceptance'                    
        ports:
        - containerPort: 7600
        - containerPort: 7800
        - containerPort: 9483
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: ace
  labels:
    app: ace
  namespace: ace
spec:
  ports:
  - name: http
    port: 7600
    targetPort: 7600
  - name: http2
    port: 7800
    targetPort: 7800  
  selector:
    app: ace
  type: LoadBalancer
