apiVersion: v1
kind: Namespace
metadata:
  name: dotnetcore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherforecast
  namespace: dotnetcore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherforecast
      stage: prod
      release: stable
      tier: "application"
      product: "weatherforecast"
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
        dynatrace/instrument: 'false'
        pipeline.stage: prod-stable
        pipeline.build: 2.3.1.3476
        pipeline.project: weatherforecast
        support.contact: 'john.doe@weatherforecast.com'
        support.channel: '#support-weatherforecast-services'
      labels:
        app: weatherforecast
        stage: prod
        release: stable
        tier: 'application'
        product: 'weatherforecast'
    spec:
      containers:
      - name: ace
        image: wabbo/mydotnetcoreapi:latest
        env:
        - name: NODENAME
          value: MYNODE
        - name: SERVERNAME
          value: MYMBSERVER
        - name: LICENSE
          value: accept
        - name: DT_CLUSTER_ID
          value: 'dotnetcoreapi-production'
        - name: DT_RELEASE_BUILD_VERSION
          value: '2021-12-12'          
        - name: DT_RELEASE_VERSION
          value: '1.0.1'
        - name: DT_RELEASE_PRODUCT
          value: 'Weather Forecast'
        - name: DT_RELEASE_STAGE
          value: 'User-Acceptance'                    
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: weatherforecast
  labels:
    app: weatherforecast
  namespace: dotnetcore
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: weatherforecast
  type: LoadBalancer
